// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWKqbBC6u0gvMhcv3oA055GDPfWOh64Qo',
    appId: '1:55267118613:web:5a7548492c8365a6e6481c',
    messagingSenderId: '55267118613',
    projectId: 'cashrich-fdf38',
    authDomain: 'cashrich-fdf38.firebaseapp.com',
    storageBucket: 'cashrich-fdf38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhJ10Rcgt5bC67E8XM-hGpgyhabJrTcOo',
    appId: '1:55267118613:android:8eaf290f93c7dbe8e6481c',
    messagingSenderId: '55267118613',
    projectId: 'cashrich-fdf38',
    storageBucket: 'cashrich-fdf38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9HRGNTNgxZ74g1iUJcB7V2pQNPZOsNlI',
    appId: '1:55267118613:ios:f8ddc537df574e7ce6481c',
    messagingSenderId: '55267118613',
    projectId: 'cashrich-fdf38',
    storageBucket: 'cashrich-fdf38.appspot.com',
    iosClientId: '55267118613-efjhsf9rrp7m7c7md25pa3u11uth5dus.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashrich',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9HRGNTNgxZ74g1iUJcB7V2pQNPZOsNlI',
    appId: '1:55267118613:ios:f8ddc537df574e7ce6481c',
    messagingSenderId: '55267118613',
    projectId: 'cashrich-fdf38',
    storageBucket: 'cashrich-fdf38.appspot.com',
    iosClientId: '55267118613-efjhsf9rrp7m7c7md25pa3u11uth5dus.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashrich',
  );
}
